# Generated by Django 6.0.6 on 2026-08-17 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='categoryImage')),
            ],
        ),
    ]
