# Generated by Django 6.1 on 2026-08-17 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AccountApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='last_ame',
            new_name='last_name',
        ),
    ]
