# Generated by Django 6.1 on 2026-08-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountApp', '0002_rename_last_ame_account_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phoneNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
