# Generated by Django 6.1 on 2026-09-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountApp', '0004_account_addressline1_account_addressline2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='addressLine1',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='account',
            name='addressLine2',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='account',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='account',
            name='state',
            field=models.CharField(max_length=100),
        ),
    ]
