# Generated by Django 6.1 on 2026-09-07 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AccountApp', '0005_alter_account_addressline1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='addressLine1',
        ),
        migrations.RemoveField(
            model_name='account',
            name='addressLine2',
        ),
        migrations.RemoveField(
            model_name='account',
            name='city',
        ),
        migrations.RemoveField(
            model_name='account',
            name='state',
        ),
    ]
