# Generated by Django 6.1 on 2026-08-21 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CartApp', '0002_cartitem_variations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='variations',
            new_name='variation',
        ),
    ]
