# Generated by Django 6.1 on 2026-09-07 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CartApp', '0005_billingaddress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BillingAddress',
        ),
    ]
